/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApplicantCard: typeof import('./components/ApplicantCard.vue')['default']
    Applicants: typeof import('./components/Applicants.vue')['default']
    ApplicationsTable: typeof import('./components/ApplicationsTable.vue')['default']
    copy: typeof import('./components/resultsDetails copy.vue')['default']
    DevBoard: typeof import('./components/DevBoard.vue')['default']
    DisplayResults: typeof import('./components/DisplayResults.vue')['default']
    'DisplayResults copy': typeof import('./components/DisplayResults copy.vue')['default']
    Exports: typeof import('./components/Exports.vue')['default']
    Facilities: typeof import('./components/Facilities.vue')['default']
    GoogleDriveManagement: typeof import('./components/GoogleDriveManagement.vue')['default']
    GradeBubbleSheet: typeof import('./components/GradeBubbleSheet.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LookupUsers: typeof import('./components/LookupUsers.vue')['default']
    'LookupUsers copy': typeof import('./components/LookupUsers copy.vue')['default']
    Mavericks: typeof import('./components/Mavericks.vue')['default']
    MergeApplicants: typeof import('./components/MergeApplicants.vue')['default']
    ProcessLogs: typeof import('./components/ProcessLogs.vue')['default']
    ProcessLogsTable: typeof import('./components/ProcessLogsTable.vue')['default']
    Queue: typeof import('./components/Queue.vue')['default']
    RegularMail: typeof import('./components/RegularMail.vue')['default']
    ReportExports: typeof import('./components/ReportExports.vue')['default']
    ResultsDetails: typeof import('./components/resultsDetails.vue')['default']
    'ResultsDetails copy': typeof import('./components/resultsDetails copy.vue')['default']
    RosterReport: typeof import('./components/RosterReport.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    ThankYouNotes: typeof import('./components/ThankYouNotes.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    TopNavbar: typeof import('./components/TopNavbar.vue')['default']
    UploadFiles: typeof import('./components/UploadFiles.vue')['default']
  }
}
