/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dev': RouteRecordInfo<'/dev', '/dev', Record<never, never>, Record<never, never>>,
    '/facilities': RouteRecordInfo<'/facilities', '/facilities', Record<never, never>, Record<never, never>>,
    '/mail': RouteRecordInfo<'/mail', '/mail', Record<never, never>, Record<never, never>>,
    '/mavericks': RouteRecordInfo<'/mavericks', '/mavericks', Record<never, never>, Record<never, never>>,
    '/queue': RouteRecordInfo<'/queue', '/queue', Record<never, never>, Record<never, never>>,
    '/results': RouteRecordInfo<'/results', '/results', Record<never, never>, Record<never, never>>,
  }
}
